apiVersion: v1
kind: ConfigMap
metadata:
  name: server-side-configs
data:
  PORT: "5000"
#  CLIENT: <front-end-app-service-ip>:<port>
  CLIENT: http://192.168.49.2:30756
  MONGODB_URL: mongodb://todo-mongo-service:27017/todo-k8s
